title: "Student Journal Club on Experimental Medicine"
description: This is the website of the student journal club on experimental medicine at University Hospital Frankfurt (Germany).

author: Paul Mennig
email: pmu@mail.de

theme: minima

minima:
social_links:
  - { platform: github,  user_url: "https://github.com/pmaen" }
  - { platform: linkedin,  user_url: "https://www.linkedin.com/in/paul-mennig" }
footer_links:
  - title: Impressum
    url: /impressum/


