title: "JC Exp Med"
description: This is the website of the Student Journal Club on Experimental Medicine at University Hospital Frankfurt (Germany).

author: Paul Mennig
email: pmu@mail.de
github: "https://github.com/pmaen"
linkedin: "https://www.linkedin.com/in/paul-mennig"

theme: minima

minima:
footer_links:
  - title: Impressum
    url: /impressum/
  - title: Datenschutz
    url: /datenschutz/

