theme: minima
title: "YML"
description: "This is the website of the student journal club on experimental medicine at Univeristy Hospital Frankfurt (Germany)."

author :
  name : Paul Mennig
  email : pmu@mail.de
  location : Frankfurt (Germany)
  linkedin : paul-mennig
