title: "Student Journal Club on Experimental Medicine"
description: "Legal:\n This Journal Club is in no way affiliated with the Journal of Experimental Medicine or the Rockefeller University Press. Contributions are in no way limited to this journal or any other journal of the publisher.\n Logo: © dreamrice (Vecteezy) & Paul Mennig"

author: "Author: Paul Mennig\n This website is a private project that is not connected with any business activity and does not publish any journalistic-editorial content. Therefore, the imprint obligation according to § 5 TMG and § 18 MStV is not applicable. The contributor of the website can be reached at [pmu@mail.de](mailto:pmu@mail.de).\n Es handelt sich bei dieser Website um ein privates Projekt, das mit keinerlei Geschäftstätigkeit in Verbindung steht und keine journalistisch-redaktionell gestalteten Inhalte veröffentlicht. Somit entfällt die Impressumspflicht nach § 5 TMG und § 18 MStV. Der Beitreiber der Website kann unter [pmu@mail.de](mailto:pmu@mail.de) erreicht werden."

theme: minima

minima:
  social_links:
    - { platform: github,  user_url: "https://github.com/pmaen" }
    - { platform: linkedin,  user_url: "https://www.linkedin.com/in/paul-mennig" }
