title: "Student Journal Club on Experimental Medicine"
description: "Legal:
This Journal Club is in no way affiliated with the Journal of Experimental Medicine or the Rockefeller University Press. Contributions are in no way limited to this journal or any other journal of the publisher.
Logo: © dreamrice (Vecteezy) & Paul Mennig
"

author:
  name: Paul Mennig
  email: pmu@mail.de

theme: minima

minima:
  social_links:
    - { platform: github,  user_url: "https://github.com/pmaen" }
    - { platform: linkedin,  user_url: "https://www.linkedin.com/in/paul-mennig" }
